Added enum encoding to JSON dumps.
SituDevelopment/entegy-sdk-python pull request #181
Opened 2024-03-18 02:05 UTC by andre-at-situ

Added changes to the wrapper required for tests to pass in integro-backend.
Tested by running integro-backend tests.

The SESSION_SEGMENT change is still a little suspect - Entegy might actually have the spelling error in their API.

2024-03-18 03:04 UTC, willsawyerrrr requested changes

2024-03-18 03:19 UTC, willsawyerrrr commented
Confirming that the template type changes are accurate. Tested as follows:

> In order to click the below links, you must have most recently accessed the project titled 'Will Test Project' (project number 32588) in Entegy

```python
>>> from entegywrapper import EntegyAPI
>>>
>>> api = EntegyAPI(...)
>>>
>>> api.get_content("SessionSegment", module_id=3)
Content(...)  # representing https://situ.entegysuite.com.au/Schedule/SessionSegmentEdit/3
>>> api.get_content("SessionSegement", module_id=3)
entegywrapper.errors.EntegyNoDataError: No content returned
>>> api.get_content("FloorPlan", module_id=10)
Content(...)  # representing https://situ.entegysuite.com.au/Contents/Edit/96/10
>>> api.get_content("FloorPlans", module_id=7)
Content(...)  # representing https://situ.entegysuite.com.au/Contents/Edit/95/7
```

2024-03-18 04:25 UTC, andre-at-situ commented on entegywrapper/__init__.py
> +    return json.dumps(obj, cls=EnumJSONEncoder, **kwargs)
Updated.

2024-03-18 04:26 UTC, andre-at-situ commented on entegywrapper/content/content.py
> +    self: EntegyAPI, content: dict[str, Any], *, content_group: str = "Default"
Updated.

2024-03-19 04:13 UTC, andre-at-situ commented on entegywrapper/content/content.py
> +    self: EntegyAPI, content: dict[str, Any], *, content_group: str = "Default"
I've kicked the can down the road on this one. See: https://github.com/SituDevelopment/entegy-sdk-python/issues/184

2024-03-19 04:13 UTC, andre-at-situ commented on entegywrapper/content/content.py
> +    children: list[dict[str, Any]],
I've kicked the can down the road on this one. See: https://github.com/SituDevelopment/entegy-sdk-python/issues/184

2024-03-19 04:13 UTC, andre-at-situ commented
> Confirming that the template type changes are accurate. Tested as follows:
> 
> > In order to click the below links, you must have most recently accessed the project titled 'Will Test Project' (project number 32588) in Entegy
> 
> ```python
> >>> from entegywrapper import EntegyAPI
> 
> >>> api = EntegyAPI(...)
> 
> >>> api.get_content("SessionSegment", module_id=3)
> Content(...)  # representing https://situ.entegysuite.com.au/Schedule/SessionSegmentEdit/3
> 
> >>> api.get_content("SessionSegement", module_id=3)
> entegywrapper.errors.EntegyNoDataError: No content returned
> 
> >>> api.get_content("FloorPlan", module_id=10)
> Content(...)  # representing https://situ.entegysuite.com.au/Contents/Edit/96/10
> 
> >>> api.get_content("FloorPlans", module_id=7)
> Content(...)  # representing https://situ.entegysuite.com.au/Contents/Edit/95/7
> ```

Nice.. ty.

2024-03-19 04:45 UTC, willsawyerrrr requested changes

2024-03-19 04:45 UTC, willsawyerrrr commented on entegywrapper/schemas/content.py
> +    def get_updated_content(self, other: "Content") -> dict[str, Any]:
Instead of manually stringifying the type annotation, can you try `from __future__ import annotations`?

2024-03-19 04:45 UTC, willsawyerrrr commented on entegywrapper/schemas/content.py
> +    moduleId: Optional[int]  # Optional when creating, not optional when retrieving.
This class represents what's retrieved, so it shouldn't be optional.
It should be optional down in the `ContentCreate` class which represents what's being created.

2024-03-19 04:45 UTC, willsawyerrrr commented on entegywrapper/schemas/content.py
> +        return updated_content
I think this should be more dynamic. Consider something like the below:

```suggestion
        updated_content = {}
        diff = lambda field: getattr(self, field) != getattr(other, field)

        for field in filter(diff, self.__class__.model_fields.keys()):
            updated_content[field] = getattr(other, field)

        return updated_content
```

or an equivalent comprehension:
        
```suggestion
        return {
            field: getattr(other, field)
            for field in self.__class__.model_fields
            if getattr(self, field) != getattr(other, field)
        }
```

See the [`BaseModel.model_fields` docs](https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.model_fields).

2024-03-25 04:33 UTC, andre-at-situ commented on entegywrapper/schemas/content.py
> +    def get_updated_content(self, other: "Content") -> dict[str, Any]:
Cool.. I didnt know you could do that.

2024-03-25 04:33 UTC, andre-at-situ commented on entegywrapper/schemas/content.py
> +    def get_updated_content(self, other: "Content") -> dict[str, Any]:
Updated.

2024-03-25 05:14 UTC, willsawyerrrr approved these changes

2024-03-25 05:15 UTC, merged