Update as per changes to integro-backend.
SituDevelopment/entegy-sdk-python pull request #188
Opened 2024-03-28 06:59 UTC by andre-at-situ

## Description

Added a number of small changes based on tests run in Integro backend. Might have to version bump again.

## Type of change

-   [x] Bug fix (non-breaking change which fixes a bug)
-   [x] Chore (non-breaking change that refactors, tidies up or formats code)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Check-in for breaking change (if applicable)

-   [x] Those packages/repos that depend on this repo have been updated for the breaking change.

## How Has This Been Tested?

Tests have been run successfully in integro-backend.

## Checklist:

-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2024-03-28 07:30 UTC, willsawyerrrr requested changes

2024-03-28 07:30 UTC, willsawyerrrr commented on entegywrapper/content/categories.py
> +        `categories` (`list[Union[Category, ContentCreate]]`): the categories to create
```suggestion
        `categories` (`list[Category | ContentCreate]]`): the categories to create
```

Prefer `|` over `Union`. This is also consistent with the syntax in the method signature.

2024-03-28 07:30 UTC, willsawyerrrr commented on entegywrapper/content/categories.py
> +    response = self.post(self.api_endpoint + "/v2/Categories/Delete", data=data)
[Docs](https://situ.entegysuite.com.au/Docs/Api/content-delete) suggest this should use `DELETE`.

2024-04-03 23:21 UTC, andre-at-situ commented on entegywrapper/content/categories.py
> +    response = self.post(self.api_endpoint + "/v2/Categories/Delete", data=data)
Aha.. they do.. but that doesn't work hence the change... thanks for your accurate API doc updates Entegy!

This function is under test now as well. So if they ever change it to what its meant to be we'll know.

2024-04-04 02:42 UTC, willsawyerrrr commented on entegywrapper/content/categories.py
> +from typing import TYPE_CHECKING, Any, Optional, Union
This import is no longer needed.

Approved pending its removal.

2024-04-04 23:38 UTC, andre-at-situ commented on entegywrapper/content/categories.py
> +from typing import TYPE_CHECKING, Any, Optional, Union
Done.

2024-04-04 23:38 UTC, merged